import numpy as np

## 1. Create a NumPy array containing integers from 0 to 9.

In [2]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2. Create a NumPy array from a given Python list [10, 20, 30, 40, 50].

In [3]:
list1 = [10, 20, 30, 40, 50]
arr = np.array(list1)
arr

array([10, 20, 30, 40, 50])

## 3. Create a 2D array (3x3) with values ranging from 0 to 8.

In [11]:
arr = np.arange(0,9)
arr = arr.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 4. Given a 2D array, find its shape and size. Create a 5x4 array with random integers between 1 and 100, and print the shape and size.

In [12]:
arr.shape

(3, 3)

In [13]:
array = np.random.randint(1,100,20).reshape(5,4)
array

array([[28, 66, 61,  7],
       [51, 83, 85,  6],
       [63, 19, 12, 69],
       [44, 33, 35, 39],
       [74, 37, 11, 81]], dtype=int32)

## 5. Create a 3x3 array of integers and access:

In [14]:
matrix = np.arange(1,10).reshape(3,3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
# a. The second element of the first row.

matrix[0,1]

np.int64(2)

In [17]:
# b. The third column of the 2nd row.

matrix[1,2]

np.int64(6)

In [22]:
# c. A subarray with the first two rows and last two columns.

firstTwoRows = matrix[0:2,]
lastTwoRows = matrix[1:3,]

subarray = np.append(firstTwoRows,lastTwoRows)
subarray

array([1, 2, 3, 4, 5, 6, 4, 5, 6, 7, 8, 9])

# 6. Create a 1D array of 12 elements. Reshape it into a 3x4 2D array.

In [23]:
array = np.arange(1,13).reshape(3,4)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 7. Reshape a 3x3 matrix into a 1D array.

In [26]:
array = np.random.randint(1,20,9).reshape(3,3)
array.reshape(9,)

array([10,  6,  3,  7, 14, 19, 19,  1, 12], dtype=int32)

# 8. Create two arrays of shape (2, 3): arr1 and arr2. Perform element-wise addition, subtraction, multiplication, and division on them.

In [28]:
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(11,17).reshape(2,3)

In [29]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr2

array([[11, 12, 13],
       [14, 15, 16]])

In [32]:
# Addition

add = arr1 + arr2
add

array([[12, 14, 16],
       [18, 20, 22]])

In [33]:
# Substraction

sub = arr1 - arr2
sub

array([[-10, -10, -10],
       [-10, -10, -10]])

In [34]:
# Multiplication

mul = arr1 * arr2
mul

array([[11, 24, 39],
       [56, 75, 96]])

In [35]:
# Division

div = arr2 // arr1
div

array([[11,  6,  4],
       [ 3,  3,  2]])

# 9. Use NumPy's built-in functions to compute the sum, mean, and standard deviation of a given array.

In [36]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
# Sum

add = arr.sum()
add

np.int64(45)

In [38]:
# Mean

arrMean = arr.mean()
arrMean

np.float64(5.0)

In [40]:
# Standard Deviation
mArr = arr.reshape(3,3)
mArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
colSTD = np.std(mArr, axis=1)
colSTD

array([0.81649658, 0.81649658, 0.81649658])

In [42]:
rowSTD = np.std(mArr, axis=0)
rowSTD

array([2.44948974, 2.44948974, 2.44948974])

# 10. Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or the @ operator.

A = np.arange(1,5).reshape(2,2)
B = np.arange(6,10).reshape(2,2)

In [44]:
A

array([[1, 2],
       [3, 4]])

In [45]:
B

array([[6, 7],
       [8, 9]])

In [46]:
# Multiplication using np.dot()

mul = np.dot(A,B)
mul

array([[22, 25],
       [50, 57]])

In [47]:
# Multiplication using @ operator

OpMul = A @ B
OpMul

array([[22, 25],
       [50, 57]])

## 11. Find the transpose of matrix A and matrix B.

In [48]:
TofA = A.T
TofA

array([[1, 3],
       [2, 4]])

In [49]:
TofB = B.T
TofB

array([[6, 8],
       [7, 9]])

## 12. Create a 3x3 array and a 1D array with 3 elements. Add the 1D array to the 2D array. Explain how broadcasting works in this operation.

In [50]:
matrix = np.arange(1,10).reshape(3,3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [53]:
add = arr + matrix
add

# In this Case, the 1D array will add in each row of the 2D array in each element and that's how the Broadcasting work in this case

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

# 13. Create a 4x4 array of random integers. Find the maximum, minimum, and mean of the entire array.

In [54]:
arr = np.random.randint(1,50,16).reshape(4,4)
arr

array([[38, 44, 35, 18],
       [25, 35, 25, 18],
       [40, 24, 46, 35],
       [47, 25,  4,  1]], dtype=int32)

In [55]:
arr.min()

np.int32(1)

In [56]:
arr.max()

np.int32(47)

In [57]:
arr.mean()

np.float64(28.75)

# 14. Find the row-wise and column-wise sums.

In [58]:
arr

array([[38, 44, 35, 18],
       [25, 35, 25, 18],
       [40, 24, 46, 35],
       [47, 25,  4,  1]], dtype=int32)

In [61]:
arr.sum(axis=1)

array([135, 103, 145,  77])

In [62]:
arr.sum(axis=0)

array([150, 128, 110,  72])

# 15. Generate an array of 10 random integers between 1 and 50.

In [63]:
arr = np.random.randint(1,50,10)
arr

array([12, 17, 12, 14,  6, 28, 35, 14, 33, 40], dtype=int32)

# 16. Generate a 5x5 matrix of random floats between 0 and 1.

In [71]:
zero = np.random.random(25).reshape(5,5)
zero

array([[0.87633859, 0.09066176, 0.25530425, 0.47699223, 0.14535161],
       [0.40882318, 0.11236479, 0.2668771 , 0.65465826, 0.62294195],
       [0.43826391, 0.95032843, 0.33257505, 0.24044985, 0.63041417],
       [0.18747612, 0.84815747, 0.32363066, 0.72857478, 0.52487893],
       [0.65255785, 0.29464878, 0.36550817, 0.33615969, 0.40938992]])