In [1]:
import numpy as np

## 1. Write code to create a 4x3 matrix with values ranging from 2 to 13.

In [4]:
matrix = np.arange(2,14).reshape(4,3)
matrix

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

## 2. Write code to replace the odd numbers by -1 in the array created by using random.randint( 1 , 50,20)

In [5]:
arr = np.random.randint(1,50,20)
arr

array([22, 13, 48, 19, 42, 37, 13, 34, 45, 31,  5, 45, 12, 37,  6, 34,  8,
        1, 17, 47], dtype=int32)

In [6]:
arr[arr%2!=0] = -1

In [7]:
arr

array([22, -1, 48, -1, 42, -1, -1, 34, -1, -1, -1, -1, 12, -1,  6, 34,  8,
       -1, -1, -1], dtype=int32)

## 3. Perform the following operations on an array of mobile phones prices 6999, 7500, 11999, 27899, 14999, 9999.

In [44]:
# a. Create a 1d-array of mobile phones prices

prices = np.array([6999,7500,11999,27899,14999,9999])
prices

array([ 6999,  7500, 11999, 27899, 14999,  9999])

In [45]:
# b. Convert this array to float type

prices = prices.astype(float)
prices.dtype

dtype('float64')

In [46]:
# c. Append a new mobile having price of 13999 Rs. to this array

prices = np.append(prices,13999)

In [47]:
prices

array([ 6999.,  7500., 11999., 27899., 14999.,  9999., 13999.])

In [48]:
# d. Reverse this array of mobile phones prices
np.flip(prices)

array([13999.,  9999., 14999., 27899., 11999.,  7500.,  6999.])

In [49]:
# e. Apply GST of 18% on mobile phones prices and update this array.

prices = prices * 1.18
prices

array([ 8258.82,  8850.  , 14158.82, 32920.82, 17698.82, 11798.82,
       16518.82])

In [52]:
# f. Sort the array in descending order of price

np.sort(prices)

array([ 8258.82,  8850.  , 11798.82, 14158.82, 16518.82, 17698.82,
       32920.82])

In [53]:
# g. What is the average mobile phone price
prices.mean()

np.float64(15743.560000000001)

In [56]:
# h. What is the difference b/w maximum and minimum price

diff = prices.max() - prices.min()
diff

np.float64(24662.0)

## 4. Find out the indices of non zero element in given array [1,2,0,0,4,0]

In [61]:
arr = np.array([1,2,0,0,4,0])
arr

array([1, 2, 0, 0, 4, 0])

In [60]:
indices = np.argwhere(arr != 0)

array([1, 2, 4])